apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: jwt-secret
  namespace: default
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: SecretStore
  target:
    name: jwt-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        JWT_SECRET: "{{ .secret }}"
        JWT_EXPIRATION: "{{ .expiration }}"
        JWT_REFRESH_EXPIRATION: "{{ .refresh_expiration }}"
  
  dataFrom:
    - extract:
        key: /goorm-popcorn/prod/jwt/secret-key
