apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: redis-credentials
  namespace: default
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: SecretStore
  target:
    name: redis-credentials
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        REDIS_HOST: "{{ .host }}"
        REDIS_PORT: "{{ .port }}"
        REDIS_PASSWORD: "{{ .password }}"
        
        # Spring Boot Redis 설정
        SPRING_DATA_REDIS_HOST: "{{ .host }}"
        SPRING_DATA_REDIS_PORT: "{{ .port }}"
        SPRING_DATA_REDIS_PASSWORD: "{{ .password }}"
  
  dataFrom:
    - extract:
        key: /goorm-popcorn/prod/elasticache/auth-token
