apiVersion: karpenter.k8s.aws/v1beta1
kind: EC2NodeClass
metadata:
  name: default
spec:
  # AMI 선택 전략
  amiFamily: AL2 # Amazon Linux 2
  
  # 서브넷 선택 (Private 서브넷, Multi-AZ)
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: goorm-popcorn-prod
  
  # 보안 그룹 선택
  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: goorm-popcorn-prod
  
  # IAM 역할 (role 또는 instanceProfile 중 하나만 지정)
  role: KarpenterNodeRole-goorm-popcorn-prod
  
  # 사용자 데이터 (부트스트랩 스크립트)
  userData: |
    #!/bin/bash
    set -e
    
    # EKS 부트스트랩
    /etc/eks/bootstrap.sh goorm-popcorn-prod \
      --kubelet-extra-args '--max-pods=110' \
      --b64-cluster-ca $CLUSTER_CA \
      --apiserver-endpoint $CLUSTER_ENDPOINT
    
    # CloudWatch 에이전트 설치
    wget https://s3.amazonaws.com/amazoncloudwatch-agent/amazon_linux/amd64/latest/amazon-cloudwatch-agent.rpm
    rpm -U ./amazon-cloudwatch-agent.rpm
    
    # 시스템 튜닝 (프로덕션 최적화)
    echo "net.ipv4.tcp_tw_reuse = 1" >> /etc/sysctl.conf
    echo "net.ipv4.ip_local_port_range = 1024 65535" >> /etc/sysctl.conf
    echo "net.core.somaxconn = 32768" >> /etc/sysctl.conf
    sysctl -p
  
  # 블록 디바이스 매핑
  blockDeviceMappings:
    - deviceName: /dev/xvda
      ebs:
        volumeSize: 50Gi # Prod는 더 큰 볼륨
        volumeType: gp3
        iops: 3000
        throughput: 125
        encrypted: true
        deleteOnTermination: true
  
  # 메타데이터 옵션 (보안 강화)
  metadataOptions:
    httpEndpoint: enabled
    httpProtocolIPv6: disabled
    httpPutResponseHopLimit: 2
    httpTokens: required # IMDSv2 강제
  
  # 상세 모니터링 활성화 (프로덕션)
  detailedMonitoring: true
  
  # 태그
  tags:
    Name: karpenter-node-prod
    Environment: prod
    ManagedBy: karpenter
    Project: goorm-popcorn
    CostCenter: production
