apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  name: default
spec:
  # 템플릿 정의
  template:
    metadata:
      labels:
        # Karpenter 노드 식별 레이블
        karpenter.sh/capacity-type: spot
        node-type: karpenter
        environment: dev
    
    spec:
      # EC2NodeClass 참조
      nodeClassRef:
        name: default
      
      # 요구사항 정의
      requirements:
        # 인스턴스 타입
        - key: karpenter.k8s.aws/instance-family
          operator: In
          values: ["t3"]
        
        - key: karpenter.k8s.aws/instance-size
          operator: In
          values: ["medium"]
        
        # 용량 타입 (Spot 우선)
        - key: karpenter.sh/capacity-type
          operator: In
          values: ["spot"]
        
        # 아키텍처
        - key: kubernetes.io/arch
          operator: In
          values: ["amd64"]
        
        # 가용 영역 (Dev는 단일 AZ)
        - key: topology.kubernetes.io/zone
          operator: In
          values: ["ap-northeast-2a"]
      
      # Taints (선택사항 - Spot 노드에만 배포하도록 강제)
      taints:
        - key: karpenter.sh/spot
          value: "true"
          effect: NoSchedule
      
      # Kubelet 설정
      kubelet:
        maxPods: 110
        podsPerCore: 0
        systemReserved:
          cpu: 100m
          memory: 100Mi
          ephemeral-storage: 1Gi
        kubeReserved:
          cpu: 100m
          memory: 100Mi
          ephemeral-storage: 1Gi
        evictionHard:
          memory.available: 5%
          nodefs.available: 10%
          nodefs.inodesFree: 5%
        evictionSoft:
          memory.available: 10%
          nodefs.available: 15%
          nodefs.inodesFree: 10%
        evictionSoftGracePeriod:
          memory.available: 1m
          nodefs.available: 1m30s
          nodefs.inodesFree: 2m
  
  # 리소스 제한
  limits:
    cpu: "40"      # 최대 40 vCPU (t3.medium 10개 = 20 vCPU, 여유분 포함)
    memory: 80Gi   # 최대 80GB 메모리
  
  # 중단 정책
  disruption:
    # 통합 정책 (Consolidation + Expiration)
    consolidationPolicy: WhenUnderutilized
    consolidateAfter: 30s
    
    # 노드 만료 (선택사항 - 정기적으로 노드 교체)
    expireAfter: 720h # 30일
    
    # 예산 제한 (동시에 중단 가능한 노드 수)
    budgets:
      - nodes: "10%"
        schedule: "* * * * *" # 항상 적용
      - nodes: "0"
        schedule: "0 9-17 * * MON-FRI" # 업무 시간에는 중단 금지
        duration: 8h
  
  # 가중치 (여러 NodePool이 있을 때 우선순위)
  weight: 10
