apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: default
spec:
  template:
    metadata:
      labels:
        karpenter.sh/capacity-type: spot
        node-type: karpenter
        environment: prod
    spec:
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: default

      requirements:
        - key: node.kubernetes.io/instance-type
          operator: In
          values:
            - t3.medium
            - t3.large

        - key: karpenter.sh/capacity-type
          operator: In
          values:
            - spot
            - on-demand

        - key: kubernetes.io/arch
          operator: In
          values:
            - amd64

        - key: topology.kubernetes.io/zone
          operator: In
          values:
            - ap-northeast-2a
            - ap-northeast-2c

      expireAfter: 168h

  limits:
    cpu: "100"
    memory: 160Gi

  disruption:
    consolidationPolicy: WhenEmptyOrUnderutilized
    consolidateAfter: 60s
    budgets:
      - nodes: "10%"
      - nodes: "0"
        schedule: "@daily"
        duration: 9h

  weight: 10
