apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  name: default
spec:
  # 템플릿 정의
  template:
    metadata:
      labels:
        # Karpenter 노드 식별 레이블
        karpenter.sh/capacity-type: spot
        node-type: karpenter
        environment: prod
    
    spec:
      # EC2NodeClass 참조
      nodeClassRef:
        name: default
      
      # 요구사항 정의
      requirements:
        # 인스턴스 타입 (다양한 타입으로 유연성 확보)
        - key: karpenter.k8s.aws/instance-family
          operator: In
          values: ["t3"]
        
        - key: karpenter.k8s.aws/instance-size
          operator: In
          values: ["medium", "large"]
        
        # 용량 타입 (Spot 우선, ON_DEMAND 폴백)
        - key: karpenter.sh/capacity-type
          operator: In
          values: ["spot", "on-demand"]
        
        # 아키텍처
        - key: kubernetes.io/arch
          operator: In
          values: ["amd64"]
        
        # 가용 영역 (Multi-AZ)
        - key: topology.kubernetes.io/zone
          operator: In
          values: ["ap-northeast-2a", "ap-northeast-2c"]
      
      # Taints (선택사항 - Spot 노드에만 배포하도록 강제)
      taints:
        - key: karpenter.sh/spot
          value: "true"
          effect: NoSchedule
      
      # Kubelet 설정
      kubelet:
        maxPods: 110
        podsPerCore: 0
        systemReserved:
          cpu: 200m
          memory: 200Mi
          ephemeral-storage: 2Gi
        kubeReserved:
          cpu: 200m
          memory: 200Mi
          ephemeral-storage: 2Gi
        evictionHard:
          memory.available: 5%
          nodefs.available: 10%
          nodefs.inodesFree: 5%
        evictionSoft:
          memory.available: 10%
          nodefs.available: 15%
          nodefs.inodesFree: 10%
        evictionSoftGracePeriod:
          memory.available: 2m
          nodefs.available: 2m
          nodefs.inodesFree: 3m
        # 이미지 GC 설정
        imageGCHighThresholdPercent: 85
        imageGCLowThresholdPercent: 80
  
  # 리소스 제한
  limits:
    cpu: "100"     # 최대 100 vCPU (t3.large 20개 = 80 vCPU, 여유분 포함)
    memory: 160Gi  # 최대 160GB 메모리
  
  # 중단 정책
  disruption:
    # 통합 정책 (Consolidation + Expiration)
    consolidationPolicy: WhenUnderutilized
    consolidateAfter: 60s # Prod는 더 보수적으로
    
    # 노드 만료 (정기적으로 노드 교체하여 보안 패치 적용)
    expireAfter: 168h # 7일
    
    # 예산 제한 (동시에 중단 가능한 노드 수)
    budgets:
      - nodes: "5%"
        schedule: "* * * * *" # 기본: 5%만 동시 중단
      - nodes: "0"
        schedule: "0 9-18 * * MON-FRI" # 업무 시간에는 중단 금지
        duration: 9h
      - nodes: "20%"
        schedule: "0 2 * * SUN" # 일요일 새벽에는 더 많이 중단 가능
        duration: 4h
  
  # 가중치 (여러 NodePool이 있을 때 우선순위)
  weight: 10
