---
# Karpenter 테스트용 워크로드
# 이 Deployment는 Karpenter가 새 노드를 생성하도록 트리거합니다

apiVersion: apps/v1
kind: Deployment
metadata:
  name: karpenter-test
  namespace: default
  labels:
    app: karpenter-test
spec:
  replicas: 0 # 처음에는 0으로 시작, 필요시 증가
  selector:
    matchLabels:
      app: karpenter-test
  template:
    metadata:
      labels:
        app: karpenter-test
    spec:
      # Karpenter 노드에 스케줄링
      tolerations:
        - key: karpenter.sh/spot
          operator: Exists
          effect: NoSchedule
      
      nodeSelector:
        karpenter.sh/capacity-type: spot
      
      containers:
        - name: nginx
          image: nginx:alpine
          resources:
            requests:
              cpu: 500m
              memory: 512Mi
            limits:
              cpu: 1000m
              memory: 1Gi
          ports:
            - containerPort: 80
              name: http
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5

---
# 테스트용 Service
apiVersion: v1
kind: Service
metadata:
  name: karpenter-test
  namespace: default
spec:
  selector:
    app: karpenter-test
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP

---
# HorizontalPodAutoscaler (선택사항)
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: karpenter-test
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: karpenter-test
  minReplicas: 1
  maxReplicas: 20
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
        - type: Percent
          value: 50
          periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 0
      policies:
        - type: Percent
          value: 100
          periodSeconds: 30
        - type: Pods
          value: 4
          periodSeconds: 30
      selectPolicy: Max
